#!/bin/bash
#Actiond logs help

# SNMP configs
version="-v1"
community="public"

# Assign command-line arguments to variables
uei="$1"
severity="$2"
logmsg="$3"
descr="$4"
operinstruct="$5"
nodeid="$6"
interface="$7"
parameter_name="$8"
parameter_value="$9"
matched_value = ""

# Fetch more info
sysname=$(snmpwalk "$version" -c "$community" "$interface" sysName)
sysdescr=$(snmpwalk "$version" -c "$community" "$interface" sysDescr)
sysobjectId=$(snmpwalk "$version" -c "$community" "$interface" sysObjectId)
sysupTime=$(snmpwalk "$version" -c "$community" "$interface" sysUpTime)
syscontact=$(snmpwalk "$version" -c "$community" "$interface" sysContact)
syslocation=$(snmpwalk "$version" -c "$community" "$interface" sysLocation)
sysservices=$(snmpwalk "$version" -c "$community" "$interface" sysServices)

# Matching
case $parameter_name in 
    .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.2.285278465.84)
         matched_value="Slot 1/1 : 84 ONU"
         ;;
    .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.2.285278721.84)
         matched_value="Slot 2/1 : 84 ONU"
         ;;
    *)
        matched_value="No value to Display"
        ;;
esac

# Send New enhanced Event with HTTP Post request
curl -u admin:admin \
-X POST \
-d "<event>
        <uei>$uei/enhanced/autoaction</uei>
        <interface>$interface</interface>
        <source>default</source>
        <nodeid>$nodeid</nodeid>
        <logmsg>$logmsg $descr</logmsg>
        <descr>
            $sysname  $sysobjectId  $syslocation  $syscontact  $sysupTime  $sysservices  $sysdescr
        </descr>
        <severity>Warning</severity>
        <operinstruct>$operinstruct</operinstruct>
        <alarm-data reduction-key=\"%uei%:$sysobjectId\" alarm-type=\"1\" auto-clean=\"false\"/>
    </event>" \
-H "Content-Type: application/xml" http://192.168.1.30:8980/opennms/rest/events

# Send New complete Event with HTTP Post request
curl -u admin:admin \
-X POST \
-d "<event>
        <uei>$uei/complete/autoaction</uei>
        <interface>$interface</interface>
        <source>default</source>
        <nodeid>$nodeid</nodeid>
        <logmsg>New parameter: $parameter_name;  Original Parameter Value: $parameter_value;  Matched Parameter Value: $matched_value;</logmsg>
        <descr>
            $sysname  $sysobjectId  $syslocation  $syscontact  $sysupTime  $sysservices  $sysdescr
        </descr>
        <severity>$severity</severity>
        <operinstruct>$operinstruct</operinstruct> 
        <alarm-data reduction-key=\"%uei%:$sysobjectId:$parameter_name\" alarm-type=\"1\" auto-clean=\"false\"/>
    </event>" \
-H "Content-Type: application/xml" http://192.168.1.30:8980/opennms/rest/events

# Send Event with send-event.pl
cd ~/Desktop/github/dissertacao/cenarios-teste/dev/opennms/target/opennms-32.0.0-SNAPSHOT/bin
./send-event.pl uei.opennms.org/alternative/defined/autoaction/class/unhappiness -p "uniqueIdentifier $parameter_name" -p "originalValue $parameter_value" -p "matchedValue $matched_value"