#!/bin/bash
if [ $1 = "setup" ]; then
  #first time setup
  docker-compose up -d

  #give permissions to mount folders
  cd ../mount-volumes
  sudo chmod -R 777 data-grafana data-opennms.etc data-opennms.rdd data-opennms.reports

  #start horizon and grafana after giving permissions
  docker start horizon grafana

  echo "done"
elif [ $1 = "down" ]; then
  #stops monitoring stack
  echo "command: docker-compose down -v"
  docker-compose down -v
  echo "done"

elif [ $1 = "up" ]; then
  #starts monitoring stack
  echo "command: docker-compose up -d"
  docker-compose up -d
  echo "done"

elif [ $1 = "stop" ]; then
  #stops individual services
  if [ "$#" -gt 1 ]; then
    for i in "${@:2}"; do
      echo "command: docker stop $i"
      docker stop $i
    done
    echo "done"
  else
    echo "missing arguments"
  fi

elif [ $1 = "start" ]; then
  #starts individual services
  if [ "$#" -gt 1 ]; then
    for i in "${@:2}"; do
      echo "command: docker start $i"
      docker start $i
    done
    echo "done"
  else
    echo "missing arguments"
  fi

elif [ $1 = "ls" ]; then
  #shows containers activities
  echo "command: docker-compose ps -a"
  docker-compose ps -a
  echo "done"

elif [ $1 = "test-trap" ]; then
  #shows containers activities
  echo "snmptrap -v 2c -c public localhost '' 1.3.6.1.4.1.2021.991.17 .1.3.6.1.2.1.1.6.0 s Milky Way"
  snmptrap -v 2c -c public localhost '' 1.3.6.1.4.1.2021.991.17 .1.3.6.1.2.1.1.6.0 s "Milky Way"
  echo "done"

elif [ $1 = "--help" ]; then
  #shows script capabilities
  echo -e "\ncommand: ./<scrip_name> <operation> <service>"
  echo -e "\noperations:\n  - setup\n  - up\n  - down\n  - start <services>\n  - stop <services>\n  - ls\n  - test-trap\n"
  echo -e "services:\n  - grafana\n  - horizon\n  - database\n"
else
  echo "try again"
fi
