#!/bin/bash
if [ $1 = "setup" ]; then
  #first time setup
  docker-compose up -d

  #give permissions to mount folders
  cd mount-volumes
  sudo chmod -R 777 volume-grafana
  #data-opennms.rdd data-opennms.bin

  #start grafana after giving permissions
  docker start grafana

  echo "done"

elif [ $1 = "assemble" ]; then
  #raise the open files limit
  ulimit -n 16384

  #move to opennms directory
  cd opennms

  #assemble opennms
  ./assemble.pl -p dir -DskipTests

elif [ $1 = "compile" ]; then
  #raise the open files limit
  ulimit -n 16384

  #copy kafka consumer replacement files to their corresponding directories.
  cp config/kafka/KafkaConsumerReplacementFiles/EventsMapper.java opennms/features/kafka/consumer/src/main/java/org/opennms/features/kafka/consumer/events/
  cp config/kafka/KafkaConsumerReplacementFiles/OpenNMSKafkaConsumer.java opennms/features/kafka/consumer/src/main/java/org/opennms/features/kafka/consumer/
  cp config/kafka/KafkaConsumerReplacementFiles/EventBuilder.java opennms/opennms-model/src/main/java/org/opennms/netmgt/model/events/

  #move to opennms directory
  cd opennms

  #compile opennms files
  ./compile.pl -U -DskipTests

elif [ $1 = "clean" ]; then
  #raise the open files limit
  ulimit -n 16384

  #change to opennms directory
  cd opennms

  #clean opennms target build
  ./clean.pl

elif [ $1 = "from-scretch" ]; then
  #raise the open files limit
  ulimit -n 16384

  #copy kafka consumer replacement files to their corresponding directories.
  #To access db without credentials
  cp config/kafka/KafkaConsumerReplacementFiles/pom.xml opennms-virtualization/features/kafka/consumer/
  #To be able to read XML events
  cp config/kafka/KafkaConsumerReplacementFiles/EventsMapper.java opennms-virtualization/features/kafka/consumer/src/main/java/org/opennms/features/kafka/consumer/events/
  cp config/kafka/KafkaConsumerReplacementFiles/OpenNMSKafkaConsumer.java opennms-virtualization/features/kafka/consumer/src/main/java/org/opennms/features/kafka/consumer/
  #To be able to write the Operation Instructions
  cp config/kafka/KafkaConsumerReplacementFiles/EventBuilder.java opennms-virtualization/opennms-model/src/main/java/org/opennms/netmgt/model/events/
  
  #change to opennms directory
  cd opennms-virtualization

  #clean, compile and assemle opennms
  time (./clean.pl && ./compile.pl -U -DskipTests && ./assemble.pl -Dopennms.home=/opt/opennms -DskipTests)

elif [ $1 = "down" ]; then
  #stops monitoring stack
  echo "command: docker-compose down -v"
  docker-compose down -v
  echo "done"

elif [ $1 = "up" ]; then
  #starts monitoring stack
  echo "command: docker-compose up -d"
  docker-compose up -d
  echo "done"
elif [ $1 = "stop" ]; then
  #stops individual services
  if [ "$#" -gt 1 ]; then
    for i in "${@:2}"; do
      echo "command: docker stop $i"
      docker stop $i
    done
    echo "done"
  else
    echo "missing arguments"
  fi

elif [ $1 = "start" ]; then
  #starts individual services
  if [ "$#" -gt 1 ]; then
    for i in "${@:2}"; do
      echo "command: docker start $i"
      docker start $i
    done
    echo "done"
  else
    echo "missing arguments"
  fi

elif [ $1 = "ls" ]; then
  #shows containers activities
  echo "command: docker-compose ps -a"
  docker-compose ps -a
  echo "done"

elif [ $1 = "h-terminal" ]; then
  #shows containers activities
  echo "command: docker exec -it horizon /bin/bash"
  docker exec -it horizon /bin/bash
  echo "done"

elif [ $1 = "test-trap" ]; then
  #shows containers activities
  echo "snmptrap -v 2c -c public localhost '' 1.3.6.1.4.1.2021.991.17 .1.3.6.1.2.1.1.6.0 s Milky Way"
  snmptrap -v 2c -c public localhost '' 1.3.6.1.4.1.2021.991.17 .1.3.6.1.2.1.1.6.0 s "Milky Way"
  echo "done"

elif [ $1 = "--help" ]; then
  #shows script capabilities
  echo -e "\ncommand: ./<scrip_name> <operation> <service>"
  echo -e "\noperations:\n  - setup\n  - up\n  - down\n  - start <services>\n  - stop <services>\n  - ls\n  - test-trap\n  - h-terminal\n  - clean\n  - compile\n  - assemble\n  - from-scretch\n"
  echo -e "services:\n  - grafana\n  - broker\n  - zookeeper\n  - database\n"
else
  echo "try again"
fi

